name: Deploy to GitHub pages
on:
  push:
    branches: [$default-branch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup NPM
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm build
    - run: npm export

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out
