name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - run: touch out/.nojekyll

      - name: Push to gh-pages
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -a
          git switch gh-pages
          git add out/
          git commit -m "Push out/ to gh-pages"
