name: Build and push to tim-hilt.github.io
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - run: touch out/.nojekyll

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github-push-token }}
          branch: ${{ github.ref }}
          repository: tim-hilt/tim-hilt.github.io
          directory: out

